package com.smfreports.cics;

import java.util.Objects;

/**
 * Key to keep transaction stats in hashtable, by applid, program name and transaction name
 *
 */
public class TransactionsByProgramNameKey 
{
    private String applid;
    private String programName;
    private String transaction;
    
    TransactionsByProgramNameKey(String applid, String programName, String transaction)
    {
        this.applid = applid;
        this.programName = programName;
        this.transaction = transaction;
    }   
    
    public String getApplid() {
        return applid;
    }
    
    public String getProgramName() {
        return programName;
    }

    public String getTransaction() {
        return transaction;
    }

    // hashCode and equals generated by Eclipse
    
    @Override
    public int hashCode() {
        return Objects.hash(applid, programName, transaction);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (!(obj instanceof TransactionsByProgramNameKey))
            return false;
        TransactionsByProgramNameKey other = (TransactionsByProgramNameKey) obj;
        return Objects.equals(applid, other.applid) && Objects.equals(programName, other.programName)
                && Objects.equals(transaction, other.transaction);
    }
}
