package com.smfreports.cics;

import java.util.Objects;

public class TransactionsByTxNameKey 
{
    private String applid;
    private String transaction;
    
    TransactionsByTxNameKey(String applid, String transaction)
    {
        this.applid = applid;
        this.transaction = transaction;
    }   
    
    public String getApplid() {
        return applid;
    }

    public String getTransaction() {
        return transaction;
    }

    // hashCode and equals generated by Eclipse
    
    @Override
    public int hashCode() {
        return Objects.hash(applid, transaction);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (!(obj instanceof TransactionsByTxNameKey))
            return false;
        TransactionsByTxNameKey other = (TransactionsByTxNameKey) obj;
        return Objects.equals(applid, other.applid) && Objects.equals(transaction, other.transaction);
    }
}
